### ISSUE TITLE
bullet-list and ordered-list odd behavior

### ISSUE THREAD

**Issue by SunnyCheung-cp** [Milkdown/milkdown#1148]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.30

### Steps to reproduce

When I try to type two lines of text and set each to bullet-list or ordered-list
we can see , This so confusing

https://github.com/Milkdown/milkdown/assets/105030733/7ed1c890-7d97-42d5-95aa-4f710e4d0d56

### Expected behavior

not have 

### Actual behavior

have 

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Create React App

**Comment by Saul-Mirone** [comment]
That's because the content is created as two different bullet lists, rather than one list with two different list items. If you need to auto merge those two lists, you'll need something like [join](https://prosemirror.net/docs/ref/#state.Command). The playground is just a simply demo so I didn't consider this behavior.
