### ISSUE TITLE
When I type "[", a "\" appears before "[" in the markdown source code

### ISSUE THREAD

**Issue by bent2685** [Milkdown/milkdown#1278]
### Initial checklist

- [x] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [x] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.3

### Steps to reproduce

当我输入`[`的时候，`[`的前面会出现一个多余的`\`。

导致无法使用 Link和 Img，因为Link和Img是`[`开头。在官方的Playgroud中也出现了这个现象

eg:
当我输入
```
[百度](http://www.baidu.com/)
```

在md源码中会被解析成

```
\[百度]\(http\://www\.baidu.com/)
```

最终导致Link无法显示

### Expected behavior

```
[百度](http://www.baidu.com/)
```

### Actual behavior

```
\[百度]\(http\://www\.baidu.com/)
```

### Runtime

Electron

### OS

macOS

### Build and bundle tools

Vite

**Comment by bent2685** [comment]
![image](https://github.com/Milkdown/milkdown/assets/94226447/a02ba76d-f843-49d5-963f-9899efd4b1db)

**Comment by bsdayo** [comment]
Meeting the same problem.

**Comment by chainlist** [comment]
Same here.

@Saul-Mirone do you have a plan/idea how to fix this?

**Comment by ravi-ojha** [comment]
![image](https://github.com/Milkdown/milkdown/assets/4465264/e86abdb7-d829-420c-9c91-fe8232faa993)

Same issue with using Shift+Enter and then typing anything.

**Comment by ravi-ojha** [comment]
Been debugging the last couple of hours and found the issue is with `remark-stringify`

**Comment by DanielPower** [comment]
I'm seeing this as well. If I include a [ in the initial value, it is parsed correctly and links work. But if a [ is typed into the editor, it is escaped with \. This means links are impossible to create in the editor, including in the Playground.

**Comment by DanielPower** [comment]
I've tested that this issue was introduced in 7.3.3 and still exists in 7.3.6. Reverting to 7.3.2 resolves the problem.

**Comment by Saul-Mirone** [comment]
> I've tested that this issue was introduced in 7.3.3 and still exists in 7.3.6. Reverting to 7.3.2 resolves the problem.

That part was extracted as `@milkdown/plugin-automd`. You can install the plugin and enable it.

**Comment by DanielPower** [comment]
Is the escaping of square brackets intentional, or is it a bug that will be resolved at some point? I'm writing a plugin for wiki links, which uses square brackets. Is the expectation that I need to write an InputRule that removes escaped brackets?

Is plugin-automd now required for commonmark support? It doesn't appear to be documented, but links no longer work with the commonmark preset alone.

**Comment by Saul-Mirone** [comment]
> Is the escaping of square brackets intentional, or is it a bug that will be resolved at some point? I'm writing a plugin for wiki links, which uses square brackets. Is the expectation that I need to write an InputRule that removes escaped brackets?
> 
> Is plugin-automd now required for commonmark support? It doesn't appear to be documented, but links no longer work with the commonmark preset alone.


1. The escaped brackets is introduced by `remark`, it will add escape mark to squre bracket to make sure the brackets won't be parsed as links.

2. If you really want to inseart a link instead of bracket, there're a lot of methods to do that. For example, an inputrule should be created to convert patterns like `[\w+](\w+)` into links. You can also use a shortcut to add link to the selected text.

3. For plugin-automd. It tries to reparse everything in user input and it will introduce other issues. So I split it out from `preset-commonmark` to let users to decide if they need to use it. I plan to add another inputrule for links but I just didn't get time to do that. I'm working on the [`@milkdown/components`](https://milkdown-storybook.vercel.app/?path=/story/components-code-block--javascript) and [`@milkdown/crepe`](https://milkdown-storybook.vercel.app/?path=/story/crepe-main--width-default-value) libraries.

**Comment by bent2685** [comment]
@Saul-Mirone
Thank you! I took your advice and added @milkdown/plugin-automd, then enabled it, which fixed the problem.
