### ISSUE TITLE
[Bug] undo/redo after scrolling doesn't show the result of the redo

### ISSUE THREAD

**Issue by benatkin** [Milkdown/milkdown#1361]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.5

### Steps to reproduce

Type "hello" below the header on https://milkdown.dev/playground

Press Command-down to go to the bottom

Press Ctrl-Z to undo. It scrolls to the top.

Press Ctrl-shift-z to redo. It scrolls back to the bottom.

[undo-redo.webm](https://github.com/Milkdown/milkdown/assets/4126/a9ed7b8c-c252-4ab3-83a7-8f2bab07fb04)

### Expected behavior

It should stay at the top so the user can see "Hello" after ctrl-shift-z

### Actual behavior

It scrolls to the bottom where ctrl-z was typed

### Runtime

Chrome

### OS

macOS

**Comment by Saul-Mirone** [comment]
In fact that's the expected behavior. Prosemirror based editors (like tiptap, remirror, prosekit) all behaved the same because the behavior is actually provided by [prosemirror-history](https://github.com/ProseMirror/prosemirror-history/tree/master). I remember there were some discussion about the behavior in the prosemirror community. I think the cursor restore should be considered as a feature.

**Comment by benatkin** [comment]
It isn't familiar to me. What's more familiar is how CodeMirror, vscode, and Google Docs behave - the restored text is visible upon pressing <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>Z</kbd>

**Comment by Saul-Mirone** [comment]
You can still customize the behavior if it doesn't fit your needs.
