### ISSUE TITLE
[Feature] A way to convert/change headings or text

### ISSUE THREAD

**Issue by nam-co** [Milkdown/milkdown#1543]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

Milkdown does look good, fast, but one thing I notice, if you add a H6 how do you change it in the UI for a h3? I couldn't find a way, strange

### Solution

maybe with a click on the drag icon, display heading types and p options popup

### Alternatives

click is much better than select and change

**Comment by Arcesilas** [comment]
Actually, I find the headings behavior confusing. Example:
1. Type `# Title 1` => this makes a `h1` heading
2. Add `#` right before the text `#Title 1` => you get a `h2` heading
3. Place the cursor before the text and hit `backspace` key => you get a `h1` heading, the second `#`, which you cannot see, has been deleted

I like how Obsidian handles titles and text: when you place the cursor on a heading, the `#` of the heading are shown, and you know what you are doing, since you see the `#` added or removed. They are hidden when the cursor gets out of the heading.

Also, I think the slash commands should be able to change a heading to another, or to text, or whatever is relevant (like in AppFlowy).

Maybe at least, hitting `backspace` at the beginning of a title should completly remove the heading (like in Notion): all `#` are removed and the title becomes a simple text we can change to heading with appropriate amount of `#`.

**Comment by Saul-Mirone** [comment]
You can create your own plugin to display a `#` before the heading. Milkdown is different from obsidian and notion. Obsidian and notion are apps that works out of box. Milkdown is an editor framework to build your own editor just like tiptap. You define the ux yourself. Crepe is my personal taste and used to show how to build editors on top of milkdown, if you have your own requirements of ux. It's not hard to build it yourself on top of milkdown.
