### ISSUE TITLE
[Bug] inline sync plugin breaks history plugin

### ISSUE THREAD

**Issue by Saul-Mirone** [Milkdown/milkdown#992]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.1

### Steps to reproduce

When applying emphasis to text fails, can not undo the change. For example use toggle emphasis command to create ` a_bc_d ` by playground menu bar.

### Expected behavior

Undo command works as expected.

### Actual behavior

Undo command cannot undo changes.

**Comment by Saul-Mirone** [comment]
Originally reported in https://github.com/Milkdown/milkdown/issues/989

**Comment by s524797336** [comment]
### Steps to reproduce
1. open [milkdown playground](https://milkdown.dev/playground)
2. input \*hello\* at right pane, left pane will show *hello*
3. input some thing at left pane at same line
### Expected behavior
Left pane show *hello*, right pane show \*hello\*
### Actual behavior
Breaks undo redo command and hello become bold, right pane slash lost.

Is it same thing as this issue?

**Comment by Saul-Mirone** [comment]
> ### Steps to reproduce
> 
> ```
> 
> 1. open https://milkdown.dev/playground
> 
> 2. input \*hello\* at right pane, left pane will show *hello*
> 
> 3. input some thing at left pane at same line
> 
> ```
> 
> ### Expected behavior
> 
> ```
> 
> Left pane show *hello*, right pane show \*hello\*
> 
> ```
> 
> ### Actual behavior
> 
> Breaks undo redo command and hello become bold, right pane slash lost.
> 
> 
> 
> Is it same thing as this issue?

I think so.
